{"category": "Club Service", "name": "The Beginning of A Magical Journey \u2013 CAST 4 Theme Reveal", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/the-beginning-of-a-magical-journey-cast-4-theme-reveal/", "views": "789", "date": "Oct 16, 2016"}
{"category": "Club Service", "name": "Spreading the Roots of the Rotaract Mora Family \u2013 Induction Ceremony 2016", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/induction-ceremony-2016/", "views": "619", "date": "Sep 04, 2016"}
{"category": "Club Service", "name": "\u201cLet Them Shine\u201d \u2013 21st Installation Ceremony", "author": "Featured", "url": "http://rotaractmora.org/blog/21st-installation-ceremony/", "views": "1009", "date": "Sep 05, 2016"}
{"category": "Club Service", "name": "Unlocking The Brain At The Speed Of Thought \u2013 IQ Master 2016", "author": "Chevindu Wickramathilaka", "url": "http://rotaractmora.org/blog/unlocking-brain-at-the-speed-of-thought-iq-master-2016/", "views": "945", "date": "Nov 04, 2016"}
{"category": "Club Service", "name": "\u201cRoots Evoking Spring\u201d \u2013 22nd Installation Ceremony", "author": "Featured", "url": "http://rotaractmora.org/blog/roots-evoking-spring-22nd-installation-ceremony/", "views": "449", "date": "Aug 10, 2017"}
{"category": "Club Service", "name": "Treasure Hunt of The Wizards \u2013 Refraction \u201917", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/treasure-hunt-of-the-wizards-refraction-17/", "views": "931", "date": "Mar 18, 2017"}
{"category": "Club Service", "name": "Winter Is Here, Let the battle begin! \u2013 Cast 4 Theme Reveal", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/cast-4-theme-reveal-17/", "views": "445", "date": "Sep 28, 2017"}
{"category": "Club Service", "name": "Spirits of Hope: The Faces behind the Forces", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/spirits-of-hope-the-faces-behind-the-forces/", "views": "476", "date": "Jan 01, 2016"}
{"category": "Club Service", "name": "Youth by Samuel Ullaman", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/youth-by-samuel-ullaman/", "views": "533", "date": "Jan 01, 2016"}
{"category": "Community Service", "name": "Finding the Cure Starts with Hope \u2013 Colours 1 \u2013 Hand in Hand", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/colours1-17-hih/", "views": "471", "date": "Oct 02, 2017"}
{"category": "Community Service", "name": "\u0db1\u0dd2\u0dbd\u0dca \u0d85\u0dc4\u0dc3\u0dda \u0dc0\u0dc3\u0db1\u0dca\u0dad\u0dba: Kite Festival 2016", "author": "Rotaract in Service", "url": "http://rotaractmora.org/blog/kite-festival-2016/", "views": "680", "date": "Sep 05, 2016"}
{"category": "Club Service", "name": "A Venture To Enjoy And Renew The Vigour \u2013 Board Trip", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/board-trip-a-venture-to-enjoy-and-renew-the-vigour/", "views": "484", "date": "Mar 03, 2016"}
{"category": "Professional Development", "name": "Inspire To Be True Professionals \u2013 Apprentice Phase 2", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/inspire-to-be-true-professionals-apprentice-phase-2/", "views": "921", "date": "Mar 27, 2017"}
{"category": "Professional Development", "name": "My Inspico Experience \u2013 Session at National Water Supply & Drainage Board", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/my-inspico-experience-session-at-national-water-supply-drainage-board/", "views": "284", "date": "Oct 17, 2017"}
{"category": "Professional Development", "name": "My Inspico Experience \u2013 Session at hSenid Mobile Solutions (Pvt) Ltd", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/my-inspico-experience-session-at-hsenid-mobile-solutions/", "views": "704", "date": "Oct 02, 2017"}
{"category": "Professional Development", "name": "INSPICO 2017 \u2013 Session at Arthur C Clarke Institute for Modern Technology", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/inspico-2017-session-at-arthur-c-clarke-institute-for-modern-technology/", "views": "295", "date": "Sep 20, 2017"}
{"category": "Professional Development", "name": "My Inspico Experience \u2013  Session at Camso Loadstar Wheel Manufacturing Division", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/my-inspico-experience-session-at-camso-loadstar-wheel-manufacturing-division/", "views": "155", "date": "Oct 17, 2017"}
{"category": "Professional Development", "name": "INSPICO 2017 \u2013 Session at Siam City Cement Lanka Ltd", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/inspico-2017-session-at-siam-city-cement-lanka-ltd/", "views": "321", "date": "Sep 20, 2017"}
{"category": "Professional Development", "name": "Create your perfect Resume- The Resume \u2013 Are You Ready? \u2013 2017", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/create-your-perfect-resume-the-resume-are-you-ready-2017/", "views": "282", "date": "Nov 14, 2017"}
{"category": "Club Service", "name": "REFRACTION", "author": "admin", "url": "http://rotaractmora.org/blog/refraction/", "views": "570", "date": "Jul 05, 2015"}
{"category": "Community Service", "name": "Learn. Grow. Inspire. \u2013 Inspirer \u2013 Grama Prabodhaya", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/learn-grow-inspire-inspirer-grama-prabodhaya/", "views": "1138", "date": "May 09, 2017"}
{"category": "Club Service", "name": "INDUCTION", "author": "Sakila Sandeepani", "url": "http://rotaractmora.org/blog/induction/", "views": "502", "date": "Aug 13, 2015"}
{"category": "Club Service", "name": "CLUB GET TOGETHER", "author": "Hiruni Bandara", "url": "http://rotaractmora.org/blog/club-get-together/", "views": "496", "date": "Nov 15, 2015"}
{"category": "Club Service", "name": "Cast 4- Sports day", "author": "Sakila Sandeepani", "url": "http://rotaractmora.org/blog/cast-4-sports-day/", "views": "452", "date": "Oct 18, 2015"}
{"category": "Professional Development", "name": "Pursue Your Passion \u2013 The Forum \u2013 Are You Ready? \u2013 2017", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/pursue-your-passion-the-forum-are-you-ready-2017/", "views": "373", "date": "Nov 25, 2017"}
{"category": "Professional Development", "name": "Create Your Own Trademark -YouTM \u2013 Are You Ready? -2017", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/youtm-are-you-ready-2017/", "views": "396", "date": "Nov 15, 2017"}
{"category": "Featured", "name": "Everyday Heroes", "author": "Damitha Lenadora", "url": "http://rotaractmora.org/blog/everyday-heroes/", "views": "542", "date": "Dec 11, 2016"}
{"category": "Community Service", "name": "Reaching another milestone with \u2018Grama Prabodhaya\u2019", "author": "Featured", "url": "http://rotaractmora.org/blog/reaching-another-milestone-with-grama-prabodhaya/", "views": "992", "date": "Jan 26, 2017"}
{"category": "Community Service", "name": "Grama Prabodhaya \u2013 Introductory Video", "author": "Featured", "url": "http://rotaractmora.org/blog/grama-prabodhaya-introductory-video/", "views": "950", "date": "Jan 31, 2017"}
{"category": "Featured", "name": "A Hop Step And A Jump \u2013 Wishing You All A Very Happy New Year!", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/a-hop-step-and-a-jump-wishing-you-all-a-very-happy-new-year/", "views": "779", "date": "Jan 01, 2017"}
{"category": "Professional Development", "name": "The First Impression On An Employer \u2013  The R\u00e9sum\u00e9 \u2013 Are You Ready? 2016", "author": "Madara Polgampola", "url": "http://rotaractmora.org/blog/the-first-impression-on-an-employer-the-resume-are-you-ready-2016/", "views": "598", "date": "Dec 12, 2016"}
{"category": "Professional Development", "name": "Brand Yourself In A Unique Way \u2013 YouTM \u2013 Are You Ready? 2016", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/brand-yourself-in-a-unique-way-youtm-are-you-ready-2016/", "views": "729", "date": "Dec 14, 2016"}
{"category": "Professional Development", "name": "Exclusive Eve with glamour \u2018The DEnG Workshop\u2019- Are You Ready? 2016", "author": "Natasha Kularatne", "url": "http://rotaractmora.org/blog/deg-workshop-are-you-ready2016/", "views": "885", "date": "Feb 01, 2017"}
{"category": "Professional Development", "name": "An Insight Into The Industry \u2013 The Forum \u2013 Are You Ready? 2016", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/an-insight-into-the-industry-the-forum-are-you-ready-2016/", "views": "876", "date": "Dec 13, 2016"}
{"category": "Professional Development", "name": "Do Not Let Interviews Frighten You \u2013 The Exemplar \u2013 Are You Ready? 2016", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/do-not-let-interviews-frighten-you-the-exemplar-are-you-ready-2016/", "views": "845", "date": "Jan 19, 2017"}
{"category": "Community Service", "name": "Adding Color To Their Dreams \u2013 Rainbow of Hope Phase 2 \u2013 Grama Prabodhaya", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/adding-color-to-their-dreams-rainbow-of-hope-phase-2-grama-prabodhaya/", "views": "543", "date": "May 12, 2017"}
{"category": "Community Service", "name": "Making Them Smile through the Darkness \u2013 Gift A Smile 17.2", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/3192-2/", "views": "349", "date": "Aug 18, 2017"}
{"category": "Professional Development", "name": "Have Confidence Through Your Etiquette \u2013 DE & G \u2013 Are You Ready? \u2013 2017", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/have-confidence-through-your-etiquette-de-g-are-you-ready-2017/", "views": "296", "date": "Jan 03, 2018"}
{"category": "Professional Development", "name": "Face Your Interview With Confidence- The Exemplar \u2013 Are You Ready? -2017", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/face-your-interview-with-confidence-the-exemplar-are-you-ready-2017/", "views": "284", "date": "Nov 25, 2017"}
{"category": "Community Service", "name": "Discovering the scientists within them  \u2013 Intellect \u2013 Phase 1", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/intellect-phase-1/", "views": "325", "date": "Sep 27, 2017"}
{"category": "Professional Development", "name": "Gold Chasers \u2013 Brand new initiative of Rotaract Mora", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/gold-chasers-ipho/", "views": "193", "date": "Apr 04, 2018"}
{"category": "Featured", "name": "To Whom Do Ideas Belong?", "author": "Chathurani Dias", "url": "http://rotaractmora.org/blog/to-whom-do-ideas-belong/", "views": "611", "date": "Nov 07, 2016"}
{"category": "Featured", "name": "Protect Tomorrow, Today \u2013 An Insight Into Reforest Sri Lanka With Its Co-Founder", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/protect-tomorrow-today-an-insight-into-reforest-sri-lanka-with-its-co-founder/", "views": "834", "date": "Nov 18, 2016"}
{"category": "Featured", "name": "Your job: passion or pride?", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/your-job-passion-or-pride/", "views": "592", "date": "Nov 27, 2016"}
{"category": "Featured", "name": "Black And White Keys; Can They Relate To You?", "author": "Vijini Mallawaarachchi", "url": "http://rotaractmora.org/blog/black-and-white-keys-can-they-relate-to-you/", "views": "627", "date": "Dec 05, 2016"}
{"category": "Community Service", "name": "The Tale of True Champions \u2013 Beyond Boundaries \u2013 Grama Prabodhaya", "author": "Sajeewa Jayarathne", "url": "http://rotaractmora.org/blog/the-tale-of-true-champions-beyond-boundaries-grama-prabodhaya/", "views": "845", "date": "Apr 12, 2017"}
{"category": "Professional Development", "name": "To Enhance The Writer Within \u2013 INSCRIBER", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/inscriber-to-enhance-the-writer-within/", "views": "5077", "date": "May 24, 2016"}
{"category": "Professional Development", "name": "DIMO Talk: To Perfect the Professional within", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/dimo-talk-to-perfect-the-professional-within/", "views": "501", "date": "Dec 20, 2015"}
{"category": "Professional Development", "name": "Shaping The Professionalism To Perfection \u2013 Apprentice", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/apprentice-shaping-the-professionalism-to-perfection/", "views": "731", "date": "Jun 03, 2016"}
{"category": "Professional Development", "name": "LOGO COMPETITION: A Perfect combo of Colour and Talent", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/logo-competition-a-perfect-combo-of-colour-and-talent/", "views": "771", "date": "May 04, 2016"}
{"category": "Professional Development", "name": "An Insight Into The Real Working Environment Of The Future Industry \u2013 Inspico 2016", "author": "Natasha Kularatne", "url": "http://rotaractmora.org/blog/inspico-2016/", "views": "930", "date": "Sep 05, 2016"}
{"category": "Community Service", "name": "Adding Colour To Their Dreams \u2013 Rainbow Of Hope Phase 1 \u2013 Grama Prabodhaya", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/adding-colour-to-their-dreams-rainbow-of-hope-phase-1-grama-prabodhaya/", "views": "652", "date": "Apr 17, 2017"}
{"category": "Featured", "name": "Not a Celebration, But a Reminder \u2013 World Children\u2019s Day", "author": "Natasha Kularatne", "url": "http://rotaractmora.org/blog/not-a-celebration-but-a-reminder/", "views": "621", "date": "Oct 01, 2016"}
{"category": "Community Service", "name": "Leaders Are Not Born, They Are Made \u2013 \u201cLead with Spark\u201d", "author": "Madara Polgampola", "url": "http://rotaractmora.org/blog/leaders-are-not-born-they-are-made-lead-with-spark/", "views": "657", "date": "Apr 17, 2017"}
{"category": "Community Service", "name": "Grand Opening Of The Science Laboratory \u2013 Grama Prabodhaya", "author": "Chevindu Wickramathilaka", "url": "http://rotaractmora.org/blog/grand-opening-sci-hub-grama-prabodhaya/", "views": "746", "date": "Apr 23, 2017"}
{"category": "Community Service", "name": "Grama Prabodhaya Rises and Shines In The World", "author": "Featured", "url": "http://rotaractmora.org/blog/grama-prabodhaya-rises-and-shines-in-the-world/", "views": "367", "date": "Jun 23, 2017"}
{"category": "Featured", "name": "Be The Game Changer", "author": "Vijini Mallawaarachchi", "url": "http://rotaractmora.org/blog/be-the-game-changer/", "views": "729", "date": "Oct 03, 2016"}
{"category": "Community Service", "name": "To Treat Them With A Touch of Kindness \u2013 Healing Hands 2016", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/to-treat-them-with-a-touch-of-kindness-healing-hands-2016/", "views": "1022", "date": "Feb 01, 2017"}
{"category": "Community Service", "name": "Be The Sunshine Behind A Child\u2019s Smile \u2013 Colours 2 Hand in Hand", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/be-the-sunshine-behind-a-childs-smile-colours-2-hand-in-hand/", "views": "805", "date": "Apr 05, 2017"}
{"category": "Community Service", "name": "Strengthen The Broken Strings \u2013 Hand in Hand \u2013 Hope", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/strengthen-the-broken-strings-hand-in-hand-hope/", "views": "903", "date": "Feb 26, 2017"}
{"category": "Community Service", "name": "Let Us Colour The Beach Green \u2013 Green Beach", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/let-us-colour-the-beach-green-green-beach/", "views": "873", "date": "Feb 15, 2017"}
{"category": "Professional Development", "name": "Resume", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/resume/", "views": "481", "date": "Dec 07, 2015"}
{"category": "Professional Development", "name": "EXEMPLAR", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/exemplar/", "views": "443", "date": "Dec 09, 2015"}
{"category": "Professional Development", "name": "The Flagship Day", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/the-flagship-day/", "views": "413", "date": "Dec 11, 2015"}
{"category": "Professional Development", "name": "DnG", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/dng/", "views": "517", "date": "Dec 14, 2015"}
{"category": "Community Service", "name": "In Pursuit Of Their Dreams \u2013 Grama Prabodhaya", "author": "Featured", "url": "http://rotaractmora.org/blog/in-pursuit-of-their-dreams-grama-prabodhaya/", "views": "846", "date": "Oct 11, 2016"}
{"category": "Featured", "name": "Gone Too Soon \u2013 Tribute to Rotaractor Past President Adhil Bakeer Markar", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/gone-too-soon-tribute-to-adhil-bakeer-markar/", "views": "3864", "date": "Oct 18, 2016"}
{"category": "Professional Development", "name": "Glimpse Of \u201cAre You Ready? 2015\u201d", "author": "Hiruni Bandara", "url": "http://rotaractmora.org/blog/glimpse-of-are-you-ready-2015/", "views": "557", "date": "Dec 18, 2015"}
{"category": "Featured", "name": "Do We Only See What We Want To See?", "author": "Damitha Lenadora", "url": "http://rotaractmora.org/blog/do-we-only-see-what-we-want-to-see/", "views": "543", "date": "Oct 26, 2016"}
{"category": "Featured", "name": "We Are Not Okay \u2013 Rtr. Harindi Jayasuriya", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/we-are-not-okay-rtr-harindi-jayasuriya/", "views": "414", "date": "Jun 23, 2017"}
{"category": "Featured", "name": "Pass It On \u2013 Rtr. Kashuni Kariyawasam", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/pass-it-on-rtr-kashuni-kariyawasam/", "views": "482", "date": "Jun 23, 2017"}
{"category": "Featured", "name": "Children Require More Than 600 Words \u2013 Indeewari Chandrasekara", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/children-require-more-than-600-words-indeewari-chandrasekara/", "views": "415", "date": "Jun 23, 2017"}
{"category": "Community Service", "name": "A New Home for SpongeBob \u2013 Zooxanthellae Phase 1", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/a-new-home-for-spongebob-zooxanthellae-phase-1/", "views": "595", "date": "Nov 22, 2016"}
{"category": "Featured", "name": "The Legacy Of Rotaract Mora Continues\u2026", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/the-legacy-of-rotaract-mora-continues/", "views": "368", "date": "Jul 02, 2017"}
{"category": "Featured", "name": "The Voice of Rotaract Mora Reaches High\u2026", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/the-voice-of-rotaract-mora-reaches-high/", "views": "590", "date": "Jul 02, 2017"}
{"category": "Community Service", "name": "A Wish Upon a Star \u2013 \u201cIntellect\u201d Phase 3", "author": "Sajeewa Jayarathne", "url": "http://rotaractmora.org/blog/a-wish-upon-a-star-intellect-phase-3/", "views": "604", "date": "Nov 30, 2016"}
{"category": "Featured", "name": "He is already someone", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/he-is-already-someone-cd2017/", "views": "364", "date": "Oct 01, 2017"}
{"category": "Featured", "name": "This is How I Know that You are My Friend", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/this-is-how-i-know-that-you-are-my-friend/", "views": "307", "date": "Aug 10, 2017"}
{"category": "Featured", "name": "Monthly Roundup \u2013 September", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/monthly-roundup-sep2017/", "views": "442", "date": "Oct 02, 2017"}
{"category": "Featured", "name": "Where the Wonderland Resides \u2013 World Children\u2019s Day 2017", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/childrens-day-2017/", "views": "344", "date": "Oct 01, 2017"}
{"category": "Rotaract in Service", "name": "Road To Ethnic Harmony", "author": "Paveen Perera", "url": "http://rotaractmora.org/blog/road-to-ethnic-harmony/", "views": "695", "date": "Oct 12, 2016"}
{"category": "Featured", "name": "Tis the season to love and give \u2013 Christmas wishes from Rotaract Mora", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/christmas2017/", "views": "315", "date": "Dec 24, 2017"}
{"category": "Rotaract in Service", "name": "Guide to success \u2013 Mentor Phase 3", "author": "Paveen Perera", "url": "http://rotaractmora.org/blog/guide-to-success-mentor-phase-3/", "views": "551", "date": "Oct 21, 2016"}
{"category": "Community Service", "name": "Plant A Tree, Save A River \u2013 Ganga Addara Phase 2.0", "author": "Rotaract in Service", "url": "http://rotaractmora.org/blog/plant-a-tree-save-a-river-ganga-addara-phase-2-0/", "views": "796", "date": "Nov 13, 2016"}
{"category": "Rotaract in Service", "name": "Lead The Way Phase 2 \u2013 District Leadership Development Initiative", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/lead-the-way-phase-2-district-leadership-development-initiative/", "views": "552", "date": "Dec 07, 2016"}
{"category": "Featured", "name": "TrailSL Through The Eye Of A Rotaractor", "author": "Rotaract in Service", "url": "http://rotaractmora.org/blog/trailsl-through-the-eye-of-a-rotaractor/", "views": "606", "date": "Dec 08, 2016"}
{"category": "Rotaract in Service", "name": "Making Their Dreams Real \u2013 Dream Cricket", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/making-their-dreams-real-dream-cricket/", "views": "772", "date": "Jan 17, 2017"}
{"category": "Community Service", "name": "Learning to Survive When You Are Alone \u2013 Cluster 5 Project \u2018Home Alone\u2019", "author": "Rotaract in Service", "url": "http://rotaractmora.org/blog/learning-to-survive-when-you-are-alone-cluster-5-project-home-alone/", "views": "971", "date": "Feb 21, 2017"}
{"category": "Community Service", "name": "A Day To Remember \u2013 Gift A Smile 17.1", "author": "Rotaract in Service", "url": "http://rotaractmora.org/blog/a-day-to-remember-gift-a-smile-17-1/", "views": "606", "date": "Apr 26, 2017"}
{"category": "Community Service", "name": "Towards making them intellectuals \u2013 Bridge of Hearts", "author": "Sajeewa Jayarathne", "url": "http://rotaractmora.org/blog/towards-making-them-intellectuals-bridge-of-hearts/", "views": "703", "date": "Oct 31, 2016"}
{"category": "Community Service", "name": "A Wish Upon A Star \u2013 \u201cIntellect\u201d Phase 1", "author": "Sajeewa Jayarathne", "url": "http://rotaractmora.org/blog/a-wish-upon-a-star-intellect-phase-1/", "views": "962", "date": "Oct 04, 2016"}
{"category": "Community Service", "name": "When the beacons were lit \u2013 Beacon of Hope", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/beacon-of-hope/", "views": "291", "date": "Oct 10, 2017"}
{"category": "Community Service", "name": "A Wish Upon a Star \u2013 \u201cIntellect\u201d Phase 2", "author": "Sajeewa Jayarathne", "url": "http://rotaractmora.org/blog/a-wish-upon-a-star-intellect-phase-2/", "views": "739", "date": "Oct 14, 2016"}
{"category": "Community Service", "name": "Innocent Smiles, Unsaid Words \u2013 Colours 1", "author": "Devni de Silva", "url": "http://rotaractmora.org/blog/innocent-smiles-unsaid-words-colours-1/", "views": "642", "date": "Oct 09, 2016"}
{"category": "Community Service", "name": "Give them Wings and Watch them Fly \u2013 Inspirer \u2013 Phase 1", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/give-them-wings-and-watch-them-fly/", "views": "236", "date": "Oct 31, 2017"}
{"category": "Community Service", "name": "Rotaract Mora and RAC Nallur Heritage Redefines Friendships with \u2018Leaf of Friendship\u2019", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/rotaract-mora-and-rac-nallur-heritage-lof/", "views": "248", "date": "Dec 23, 2017"}
{"category": "Community Service", "name": "Spreading the \u201cJoy of Christmas\u201d", "author": "Rotaract in Service", "url": "http://rotaractmora.org/blog/spreading-the-joy-of-christmas/", "views": "185", "date": "Jan 04, 2018"}
{"category": "Community Service", "name": "For a Healthier Tomorrow \u2013 Healing Hands\u201918", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/for-a-healthier-tomorrow-healing-hands18/", "views": "225", "date": "May 03, 2018"}
{"category": "Community Service", "name": "Journey to the world beyond the boundaries \u2013 Lokaya Dakimu \u2013 Grama Prabodhaya", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/journey-to-the-world-beyond-lokaya-dakimu-grama-prabodhaya/", "views": "313", "date": "Mar 31, 2018"}
{"category": "Community Service", "name": "Colour Their Dreams \u2013 Fit Hearts \u2013 Grama Prabodhaya", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/colour-their-dreams-fit-hearts-grama-prabodhaya/", "views": "161", "date": "Feb 19, 2018"}
{"category": "Community Service", "name": "SciWiz\u201917 \u2013 Sub-Project of Grama Prabhodaya", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/sciwiz17/", "views": "310", "date": "Jan 14, 2018"}
{"category": "Community Service", "name": "Gifting A Smile To Heal Their Hearts \u2013 Gift A Smile 18.1", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/gifting-a-smile-to-heal-their-hearts-gift-a-smile-181/", "views": "340", "date": "Feb 11, 2018"}
{"category": "Community Service", "name": "A miracle witnessed through love \u2013 Colours 2 \u2013 Hand in Hand \u201918", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/a-miracle-witnessed-through-love-colours-2-hand-in-hand-18/", "views": "27", "date": "May 30, 2018"}
{"category": "Community Service", "name": "Today\u2019s pain for Tomorrow\u2019s Strength \u2013 Hope \u2013 Hand in Hand\u201918", "author": "Koumudi Ganepola", "url": "http://rotaractmora.org/blog/todays-pain-for-tomorrows-strength-hope-hand-in-hand18/", "views": "33", "date": "May 31, 2018"}
{"category": "International Service", "name": "Warm Greetings from RCBF!", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/warm-greetings-from-rcbf/", "views": "1079", "date": "Nov 09, 2015"}
{"category": "International Service", "name": "\u201cCalling Edges\u201d: Towards fellowship without borders\u2026", "author": "Rochelle Silva", "url": "http://rotaractmora.org/blog/calling-edges-towards-fellowship-without-borders/", "views": "531", "date": "Aug 08, 2015"}
{"category": "International Service", "name": "Happiness Hour", "author": "Hiruni Bandara", "url": "http://rotaractmora.org/blog/happiness-hour/", "views": "630", "date": "Nov 28, 2015"}
{"category": "International Service", "name": "Halloween", "author": "Hiruni Bandara", "url": "http://rotaractmora.org/blog/halloween/", "views": "612", "date": "Oct 29, 2015"}
{"category": "International Service", "name": "The Sojourn Journal: Memories of the joint GM and visit to Trincomalee", "author": "Rochelle Silva", "url": "http://rotaractmora.org/blog/the-sojourn-journal-memories-of-the-joint-gm-and-visit-to-trincomalee/", "views": "947", "date": "Jan 28, 2016"}
{"category": "International Service", "name": "The Sojourn Journal: Visit to Horton Plains and Adam\u2019s Peak", "author": "Rochelle Silva", "url": "http://rotaractmora.org/blog/the-sojourn-journal-visit-to-horton-plains-and-adams-peak/", "views": "980", "date": "Jan 25, 2016"}
{"category": "International Service", "name": "The Lankan \u2013 Hong Kong Harmony and Comradeship \u2013 SPATRO", "author": "Hansadi Jayamaha", "url": "http://rotaractmora.org/blog/sojourn-the-lankan-hong-kong-harmony-and-comradeship/", "views": "735", "date": "Apr 03, 2016"}
{"category": "International Service", "name": "Hell Gone Empty, People Gone Creepy \u2013 Haunted Island 2016", "author": "Madara Polgampola", "url": "http://rotaractmora.org/blog/hell-gone-empty-people-gone-creepy-haunted-island-2016/", "views": "795", "date": "Nov 05, 2016"}
{"category": "Featured", "name": "Raconteur 2017", "author": "International Service", "url": "http://rotaractmora.org/blog/raconteur-2017/", "views": "531", "date": "Jun 01, 2017"}
{"category": "International Service", "name": "\u2018Ceylon Safari \u2013 Phase 2 \u2018 \u2013 3 Days Exploring Southern Beauties", "author": "Other", "url": "http://rotaractmora.org/blog/ceylon-safari-phase-2-3-days-exploring-southern-beauties/", "views": "234", "date": "Apr 04, 2018"}
{"category": "International Service", "name": "Ceylon Safari 2017 \u2013 Phase 1 \u2013 Exploring Dambulla and Kitulgala", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/ceylon-safari-2017-phase-1/", "views": "277", "date": "Apr 04, 2018"}
{"category": "Club Service", "name": "CAST4 : ESports", "author": "Hiruni Bandara", "url": "http://rotaractmora.org/blog/cast4-esports/", "views": "685", "date": "Apr 03, 2016"}
{"category": "International Service", "name": "Ceylon Safari \u2013 Phase 3 \u2013 Exploring the Hill Country", "author": "Amali Herath", "url": "http://rotaractmora.org/blog/ceylon-safari-phase-3-exploring-the-hill-country/", "views": "101", "date": "Apr 04, 2018"}
{"category": "Club Service", "name": "Soorya Rashmi \u2013 Awurudu Celebrations 2016", "author": "Hiruni Bandara", "url": "http://rotaractmora.org/blog/soorya-rashmi/", "views": "791", "date": "May 07, 2016"}
